name: eclipt_stylish
description: "Test project for eclipt – the stylish app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^3.0.3
  logger: ^2.6.2
  google_fonts: ^6.3.2
  go_router: ^16.3.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  email_validator: ^3.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_gen: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/app/
    - assets/images/onboarding/
    - assets/images/home/
    - assets/images/auth/
